---
deployment:
  tasks:
    - export DEPLOYPATH=/home/berandad/pwiba.berandadigital.net/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp -f .htaccess $DEPLOYPATH/.htaccess 2>/dev/null || true
    - /bin/cp -f .env.example $DEPLOYPATH/.env.example 2>/dev/null || true
